# Generated by Django 5.1.1 on 2024-11-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Addressee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Введите e-mail",
                        max_length=100,
                        unique=True,
                        verbose_name="E-mail адрес",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите Ф.И.О.",
                        max_length=150,
                        verbose_name="Фамилия Имя Отчество",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Введите комментарий", verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "адресат",
                "verbose_name_plural": "адресаты",
                "ordering": ["email", "name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Введите тему письма",
                        max_length=100,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Введите текст", verbose_name="Тело письма"
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["subject"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_mailing", models.DateField(auto_now_add=True)),
                ("end_mailing", models.DateField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Завершена"),
                            ("created", "Создана"),
                            ("launched", "Запущена"),
                        ],
                        default="created",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "addressee",
                    models.ManyToManyField(
                        help_text="Введите получателя",
                        to="message_sending.addressee",
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Введите сообщение",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message_sending.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["status"],
            },
        ),
        migrations.CreateModel(
            name="TrySending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Successfully", "Успешно"),
                            ("Unsuccessfully", "Не успешно"),
                        ],
                        default="Unsuccessfully",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message_sending.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["status"],
            },
        ),
    ]
