# Generated by Django 5.1.1 on 2024-11-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_sending", "0002_addressee_owner_mailing_owner_message_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrySending",
            new_name="Log",
        ),
    ]
