# Generated by Django 5.1.1 on 2024-11-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sending", "0003_rename_trysending_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressee",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Введите комментарий",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="end_mailing",
            field=models.DateField(blank=True, null=True),
        ),
    ]
