# Generated by Django 5.1.1 on 2024-11-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message_sending", "0004_alter_addressee_comment_alter_mailing_end_mailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log",
            options={
                "ordering": ["status"],
                "verbose_name": "попытка",
                "verbose_name_plural": "попытки",
            },
        ),
    ]
