# Generated by Django 5.1.1 on 2024-12-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sending", "0005_alter_log_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addressee",
            options={
                "ordering": ["email", "name"],
                "permissions": [("can_view_addressees", "Can view addressees")],
                "verbose_name": "адресат",
                "verbose_name_plural": "адресаты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_view_mailings", "Can view mailings"),
                    ("can_change_status", "Can change status"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "permissions": [("can_view_messages", "Can view messages")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
